version: '3'

networks:
  nocobase:
    driver: bridge

services:
  app:
    image: nocobase/nocobase:latest-full
    restart: always
    networks:
      - nocobase
    depends_on:
      - postgres
    environment:
      # The application's secret key, used to generate user tokens, etc.
      # If APP_KEY is changed, old tokens will also become invalid.
      # It can be any random string, and make sure it is not exposed.
      - APP_KEY=${APP_KEY}
      # Database type, supports postgres, mysql, mariadb
      - DB_DIALECT=${DB_DIALECT}
      # Database host, can be replaced with the IP of an existing database server
      - DB_HOST=${DB_HOST}
      # Database port
      - DB_PORT=${DB_PORT}
      # Database name
      - DB_DATABASE=${DB_DATABASE}
      # Database user
      - DB_USER=${DB_USER}
      # Database password
      - DB_PASSWORD=${DB_PASSWORD}
      # Timezone
      - TZ=${TZ}
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - '${APP_PORT}:80'
    # init: true

  # If using an existing database server, postgres service can be omitted
  postgres:
    image: postgres:16
    restart: always
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./storage/db/postgres:/var/lib/postgresql/data
    networks:
      - nocobase
